package com.tej.project.model;
// Generated 05-Oct-2018 04:00:28 by Hibernate Tools 4.3.1



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer id;
     private String fname;
     private String lname;
     private String designation;
     private int pay;
     private String department;

    public Employee() {
    }

    public Employee(String fname, String lname, String designation, int pay, String department) {
       this.fname = fname;
       this.lname = lname;
       this.designation = designation;
       this.pay = pay;
       this.department = department;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public int getPay() {
        return this.pay;
    }
    
    public void setPay(int pay) {
        this.pay = pay;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }




}


